###
POST http://localhost:8080/api/v1/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 1000
}

###
DELETE http://localhost:8080/api/v1/account
Content-Type: application/json

{
"userId": 1,
"initialBalance": 1000000000
}


###
GET http://localhost:8080/api/v1/account?user_id=2
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 1000000000
}